databases:
  - name: prescription-db
    databaseName: prescription_db
    user: prescription_user
    plan: free

services:
  - type: web
    name: prescription-db-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: prescription-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
